# Generated by Django 3.2.8 on 2021-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='restaurant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
