# Generated by Django 3.2.8 on 2021-11-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='restaurant_id',
        ),
    ]
