# Generated by Django 3.2.8 on 2021-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_ordermodel_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
