# Generated by Django 3.2.8 on 2021-11-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_menuitem_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant_id',
        ),
    ]
