# Generated by Django 3.2.8 on 2021-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20211110_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant_id',
            field=models.ManyToManyField(to='customer.Menu_list'),
        ),
    ]
