# Generated by Django 3.2.8 on 2021-11-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_menuitem_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant_id',
            field=models.ManyToManyField(related_name='item', to='customer.Menu_list'),
        ),
    ]
