# Generated by Django 3.2.8 on 2021-11-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_menuitem_restaurant_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_list',
            new_name='Restaurant_name',
        ),
    ]
