# Generated by Django 3.2.8 on 2021-11-11 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_menu_list_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant_id',
        ),
        migrations.DeleteModel(
            name='Restaurant_name',
        ),
    ]
