# Generated by Django 3.2.8 on 2021-11-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_res_name'),
        ('customer', '0013_auto_20211111_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ManyToManyField(related_name='item', to='restaurant.restaurant_model'),
        ),
    ]
