# Generated by Django 3.2.8 on 2021-11-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_model',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant_model',
            name='image',
            field=models.ImageField(default='', upload_to='menu_images/'),
            preserve_default=False,
        ),
    ]
