# Generated by Django 3.2.8 on 2021-11-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20211109_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
