# Generated by Django 3.2.8 on 2021-11-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='restaurant_name',
        ),
    ]
