# Generated by Django 3.2.8 on 2021-11-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_res_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='res_name',
        ),
    ]
